import Vapor
import Fluent

/// Controller for invites: POST /api/invites (create), GET /api/invites (validate)
struct InviteController: RouteCollection {
    func boot(routes: any RoutesBuilder) throws {
        let invites = routes.grouped("invites")
        
        // Validate is usually public or just requires the token
        // In NextAuth we only require standard validation, so no JWT required for GET
        invites.get(use: validateInvite)
        
        // Protected group for creating
        let protected = invites.grouped(JWTAuthMiddleware())
        protected.post(use: createInvite)
    }

    // POST /api/invites - Create a new invite link
    func createInvite(req: Request) async throws -> Response {
        let user = try req.auth.require(AuthenticatedUser.self)
        guard let firmaID = user.firmaID, (user.status == nil || user.status == 0) else { throw Abort(.forbidden) }
        
        struct Body: Content {
            var status: Int?
            var email: String?
        }
        let body = try req.content.decode(Body.self)
        
        // Generate secure 32 byte token -> hex string
        let token = [UInt8].random(count: 32).hex
        
        // Expires in 7 days
        let expires = Date().addingTimeInterval(7 * 24 * 60 * 60)
        
        let invite = Invite()
        invite.id = generateId()
        invite.firmaID = firmaID
        invite.userID = user.userId // Generated by this user
        invite.token = token
        invite.status = body.status ?? 0
        invite.expiresAt = expires
        
        try await invite.save(on: req.db)
        
        return try await ["token": token].encodeResponse(status: .created, for: req)
    }

    // GET /api/invites?token=XYZ
    func validateInvite(req: Request) async throws -> Response {
        guard let token = req.query[String.self, at: "token"] else {
            throw Abort(.badRequest, reason: "Missing token")
        }
        
        guard let invite = try await Invite.query(on: req.db)
            .filter(\.$token == token)
            .first() else {
            let errorRes: [String: String] = ["valid": "false", "reason": "not_found"]
            return try await errorRes.encodeResponse(for: req)
        }
        
        if invite.expiresAt < Date() {
            let errorRes: [String: String] = ["valid": "false", "reason": "expired"]
            return try await errorRes.encodeResponse(for: req)
        }
        
        struct ValidateRes: Content {
            var valid: Bool
            var firmaID: String
            var status: Int
            var inviteID: String?
        }
        return try await ValidateRes(valid: true, firmaID: invite.firmaID, status: invite.status, inviteID: invite.id).encodeResponse(for: req)
    }
}
